@if($field->type == 'Text')
    @include('records.fieldInputs.text')
@elseif($field->type == 'Rich Text')
    @include('records.fieldInputs.richtext')
@elseif($field->type == 'Number')
    @include('records.fieldInputs.number')
@elseif($field->type == 'List')
    @include('records.fieldInputs.list')
@elseif($field->type == 'Multi-Select List')
    @include('records.fieldInputs.mslist')
@elseif($field->type == 'Generated List')
    @include('records.fieldInputs.genlist')
@elseif($field->type == 'Date')
    @include('records.fieldInputs.date')
@elseif($field->type == 'Schedule')
    @include('records.fieldInputs.schedule')
@elseif($field->type == 'Geolocator')
    @include('records.fieldInputs.geolocator')
@elseif($field->type == 'Documents')
    @include('records.fieldInputs.documents')
@elseif($field->type == 'Gallery')
    @include('records.fieldInputs.gallery')
@elseif($field->type == 'Playlist')
    @include('records.fieldInputs.playlist')
@elseif($field->type == 'Video')
    @include('records.fieldInputs.video')
@elseif($field->type == '3D-Model')
    @include('records.fieldInputs.3dmodel')
@elseif($field->type == 'Associator')
    @include('records.fieldInputs.associator')
@endif