{!! Minify::javascript([
  '/assets/javascripts/vendor/jquery/jquery.js',
  '/assets/javascripts/vendor/jquery/jquery-ui.js',
  '/assets/javascripts/vendor/chosen.js',
  '/assets/javascripts/vendor/datetimepicker/jquery.datetimepicker.full.min.js',
  '/assets/javascripts/vendor/fullcalendar/moment.js',
  '/assets/javascripts/vendor/fullcalendar/fullcalendar.js',
  '/assets/javascripts/vendor/fileUpload/vendor/jquery.ui.widget.js',
  '/assets/javascripts/vendor/fileUpload/jquery.iframe-transport.js',
  '/assets/javascripts/vendor/fileUpload/jquery.fileupload.js',
  '/assets/javascripts/vendor/jplayer/jquery.jplayer.min.js',
  '/assets/javascripts/vendor/jplayer/jplayer.playlist.min.js',
  '/assets/javascripts/vendor/jsc3d/jsc3d.js',
  '/assets/javascripts/vendor/jsc3d/jsc3d.webgl.js',
  '/assets/javascripts/vendor/jsc3d/jsc3d.touch.js',
  '/assets/javascripts/vendor/slick/slick.js',
  '/assets/javascripts/general/modal.js',
  '/assets/javascripts/records/batch.js',
  '/assets/javascripts/records/create.js',
  '/assets/javascripts/records/index.js',
  '/assets/javascripts/records/show.js',
  '/assets/javascripts/records/import.js',
  '/assets/javascripts/navigation/navigation.js',
  '/assets/javascripts/general/global.js'
])->withFullUrl() !!}
